global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ['traefik:9080']

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name:        node-exporter
    scrape_interval: 30s
    static_configs:
      - targets: [ 'nodeexporter:9100' ]